esphome:
  name: "yamato"
  platform: ESP8266
  board: d1_mini
  includes:
    - yamato.h

logger:
  level: DEBUG
  baud_rate: 0

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.x.x
    gateway: 192.168.x.x
    subnet: 255.255.255.0
api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

sensor:
  - platform: uptime
    name: Interfon Uptime
  - platform: wifi_signal
    name: Interfon WiFi Signal
    update_interval: 60s
    
climate:
  - platform: custom
    lambda: |-
      auto yamato = new Yamato();
      App.register_component(yamato);
      return {yamato};
    climates:
      - name: "YamatoAC"